version: "3.9"

services:
  db:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb/initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mariadb-admin", "--user=root", "--password=${MYSQL_ROOT_PASSWORD}", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - ojs-net

  ojs:
    build:
      context: ./ojs
      dockerfile: Dockerfile
    container_name: ojs
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_AUTH=${SMTP_AUTH}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_SECURE=${SMTP_SECURE}
    ports:
      - "8080:80"
    volumes:
      - ojs_files:/var/www/html/public
      - ojs_config:/var/www/html/config
    networks:
      - ojs-net

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8080"
    networks:
      - ojs-net

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: unless-stopped
    ports:
      - "8025:8025"
    networks:
      - ojs-net

volumes:
  mariadb_data:
  ojs_files:
  ojs_config:

networks:
  ojs-net:
